### ISSUE TITLE
上传后的代码是否在Docker中运行？

### ISSUE THREAD

**Issue by hanxiao** [thunlp/CAIL2018#1]
对于这种评测系统，使用Docker container更为适合。这样的话python用户只需要一同上传requirements.txt，然后统一在docker file中使用`pip install requirements.txt`即可安装用户所需的包。这样的话，既省去了主办方手动给每个用户添加包，也保证了每个container的python环境相互独立。

不知道目前评测系统内部是如何操作的？上传后的文件是否在类似docker的虚拟机中跑？

**Comment by haoxizhong** [comment]
是在docker中运行的，但是您说的方法不太可行，因为为了防止用户通过网络获得信息，评测全程是断网的，所以没有办法通过``pip install requirements.txt``来获得安装包。
