### ISSUE TITLE
judger 代码

### ISSUE THREAD

**Issue by thisiszw** [thunlp/CAIL2018#11]
可以提供一段judger调用baseline/predictor/predictor.py生成得分的代码吗？

**Comment by haoxizhong** [comment]
1、运行svm.py训练。
2、运行python_sample里面的main.py产生svm的输出结果。
3、调用judger评分。

**Comment by thisiszw** [comment]
main.py里面有段代码
 for file_name in os.listdir(data_path):
        inf = open(os.path.join(data_path, file_name), "r")
        ouf = open(os.path.join(output_path, file_name), "w")

        fact = []

        for line in inf:
            fact.append(json.loads(line)["fact"])
            if len(fact) == get_batch():
                result = solve(fact)
                cnt += len(result)
                for x in result:
                    print(json.dumps(x), file=ouf)
                fact = []

data_path 里面应该包含哪些文件？ 不是只预测data_test.json?

**Comment by haoxizhong** [comment]
包含你要测试的文件
