### ISSUE TITLE
请求nltk安装后下载punkt

### ISSUE THREAD

**Issue by lawup** [thunlp/CAIL2018#14]
麻烦在安装nltk之后下载punkt，不然我辛辛苦苦训练的模型无法使用。谢谢啦~
报错如下：

LookupError: 
**********************************************************************
Resource [93mpunkt[0m not found.
Please use the NLTK Downloader to obtain the resource:

[31m>>> import nltk
>>> nltk.download('punkt')
[0m
Searched in:
- '/root/nltk_data'
- '/usr/share/nltk_data'
- '/usr/local/share/nltk_data'
- '/usr/lib/nltk_data'
- '/usr/local/lib/nltk_data'
- '/usr/nltk_data'
- '/usr/share/nltk_data'
- '/usr/lib/nltk_data'
- ''
**********************************************************************

**Comment by gzp9595** [comment]
已经安装
