### ISSUE TITLE
请问测试的服务器是多台吗？系统和环境是否一样?

### ISSUE THREAD

**Issue by jingyihiter** [thunlp/CAIL2018#15]
还有是服务器的系统是ubuntu16.04吗？python是3.5点几?我每次需要打开一个较大的文件（400M左右）。无论用pickle,dill,还是txt,二进制存都会有编码错误或unpicklr错误。至今已经提交过50+次了，真是心累。在本地的系统没有任何问题

**Comment by gzp9595** [comment]
是16.04  python3.5.2
出错的话，可以加一下QQ群，提供一下uid，我们看一下具体的问题
