### ISSUE TITLE
Predictor有限定是单模型的说法么？

### ISSUE THREAD

**Issue by sparkingarthur** [thunlp/CAIL2018#3]
还是说可以有多个模型，可以用模型融合？这样的话Predictor可否有自定义的多个参数传递？

**Comment by haoxizhong** [comment]
Predictor你可以理解为只是测试程序和你的程序的一个接口，我们给你的就只有事实的描述，在收到事实描述之后，你就想怎么弄怎么弄了，你的所有代码都没有必要在predict里面实现，你可以直接在predict函数里面调用你的代码即可，但是传给Predictor中predict的这个函数的只有事实这一部分，这个参数是不可变的。

**Comment by hanxiao** [comment]
@haoxizhong 

> “传给Predictor中predict的这个函数的只有事实”, 

被告`criminals`这个字段不会传给predict？

**Comment by haoxizhong** [comment]
@hanxiao 不会，这个属于额外信息，如果需要的话你需要尝试从事实部分提取该信息。
