### ISSUE TITLE
路径问题

### ISSUE THREAD

**Issue by thisiszw** [thunlp/CAIL2018#6]
代码的内容里面有提到：
“代码运行的目录并不是在predictor目录下，而是在predictor的上一级目录”
如果有一个和 predictor.py 在同一个目录下的csv文件，比如df.csv，应该如何在 predictor.py 里面读取？
import pandas as pd
df = pd.read_csv(path+"df.csv")
这里path应该用什么路径？

**Comment by haoxizhong** [comment]
path="predictor/"
