### ISSUE TITLE
Baseline 代码

### ISSUE THREAD

**Issue by thisiszw** [thunlp/CAIL2018#7]
CAIL2018/baseline/svm.py里面生成了model (joblib.dump(tfidf, 'predictor/model/tfidf.model'))

CAIL2018/baseline/predictor/predictor.py读取了model(self.tfidf = joblib.load('predictor/model/tfidf.model'))

问题：
1.打包的时候，生成model的代码必须和predictor文件夹放在同一级目录？如果有多个*.py文件和predictor文件夹在同一级目录，按什么顺序运行？

2.预测结果的代码必须放在predictor目录下？

**Comment by haoxizhong** [comment]
1.不用。无需关心运行顺序，我们只会调用predictor.py，至于你在predictor.py怎么调用，都是可以的。
2.也不用，但推荐在。并且要保证predictor.py一定在predictor下面。

**Comment by thisiszw** [comment]
所以训练模型的代码（svm.py)其实是不需要上传的，只需要把训练好的模型（'predictor/model/tfidf.model'）一起打包上传，在predictor.py里面直接调用就行了？

**Comment by haoxizhong** [comment]
yeah
