### ISSUE TITLE
多个罪名预测

### ISSUE THREAD

**Issue by thisiszw** [thunlp/CAIL2018#8]
如果一个fact对应3个罪名，是否3个全部预测正确才算True Positive？
3个罪名的顺序有关系吗，如果是，对应的法条是否也要有序？

**Comment by xcjthu** [comment]
每个类别的计算是分别独立的；
顺序没有关系

**Comment by thisiszw** [comment]
不好意思，没有描述清楚。比如下面这个判决：

{"meta": {"criminals": ["郭2某"], "term_of_imprisonment": {"death_penalty": false, "imprisonment": 60, "life_imprisonment": false}, "punish_of_money": 0, "accusation": ["盗窃", "抢夺"], "relevant_articles": [267, 264]}, "fact": "..."}

accusation 有 "盗窃", "抢夺" 两项。 这两项都需要预测到了才算True Positive 还是所预测对了一项就算True Positive。 这两项罪名有顺序吗，比如["盗窃", "抢夺"]算正确， ["抢夺", "盗窃"]则不算

**Comment by haoxizhong** [comment]
1、顺序无关
2、盗窃和抢夺的 TP是分开的 彼此没有关系

**Comment by thisiszw** [comment]
1. 顺序无关明白了
2. 盗窃和抢夺的 TP是分开的 怎么理解？

**Comment by haoxizhong** [comment]
就是说盗窃有自己的TP 每分对一个盗窃盗窃的TP+1 同理 每分对一个抢夺 抢夺的 TP+1
